### ISSUE TITLE
Localhost Not Supported

### ISSUE THREAD

**Issue by Skillz4Killz** [manyuanrong/deno_mongo#106]
When using a local version of mongodb it keeps breaking, switching to MongoDB atlas makes it work perfectly.

```ts
error: Uncaught Error: Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: failed to fill whole buffer }, ] }
      if (error) command.reject(new Error(error));
                                ^
    at Array.<anonymous> (util.ts:52:33)
    at handleAsyncMsgFromRust (core.js:182:34)
```

![image](https://user-images.githubusercontent.com/23035000/91451958-00650380-e84c-11ea-9b60-6376e5e72337.png)
![](https://cdn.discordapp.com/attachments/684898665151594506/748260974854930583/unknown.png)

![](https://cdn.discordapp.com/attachments/684898665151594506/748532165666537512/unknown.png)

MongoDB is for sure running locally and I am able to connect to it.
`Database { client: MongoClient { _clientId: 0 }, name: "dev" }`
![](https://cdn.discordapp.com/attachments/684898665151594506/748532484282646578/unknown.png)

Deno: 1.3.1
mongo: https://deno.land/x/mongo@v0.11.0/mod.ts

**Comment by hackers267** [comment]
try 0.20.0

**Comment by manyuanrong** [comment]
Are you using a Windows system? You can try the new version, which has been refactored a lot, and many problems may be resolved.
But a known problem is that Deno cannot connect to localhost correctly when establishing a connection in windows, and you need to use 127.0.0.1. This problem should be a Deno bug

**Comment by Serdnad** [comment]
Replacing `localhost` with `127.0.0.1` got things working for me on Arch linux, for version 0.22.0. Maybe this should be suggested in the README.
