### ISSUE TITLE
Couple of errors when i try to run the code on Windows machine

### ISSUE THREAD

**Issue by emmadal** [manyuanrong/deno_mongo#11]
Hello, i'm very happy to know tha a mongo driver is available with deno but there are a couple of errors when i try to execute in widows: this is the error below 
```sh
Compile https://deno.land/x/mongo@v0.5.2/mod.ts
error TS2694: Namespace 'Deno' has no exported member 'PluginOp'.
let dispatcher: Deno.PluginOp | null = null;
                     ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:7:22

error TS2339: Property 'ops' does not exist on type 'number'.
  dispatcher = Mongo.ops["mongo_command"] as Deno.PluginOp;
                     ~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:32:22

error TS2694: Namespace 'Deno' has no exported member 'PluginOp'.
  dispatcher = Mongo.ops["mongo_command"] as Deno.PluginOp;
                                                  ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:32:51

error TS2694: Namespace 'Deno' has no exported member 'OperatingSystem'.
const PLUGIN_SUFFIX_MAP: { [os in Deno.OperatingSystem]: string } = {
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:9:40

error TS7053: Element implicitly has an 'any' type because expression of type '"darwin" | "linux" | 
"windows"' can't be used to index type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  Property 'darwin' does not exist on type '{ mac?: string | undefined; linux?: string | undefined; 
win?: string | undefined; }'.
  const remoteUrl = urls[os];
                    ~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:35:21

Found 5 errors.
```
How to fix it ?

**Comment by ronhippler** [comment]
you have to use deno v0.41.0. this module is not yet updated for deno v0.42.0.

**Comment by slim-hmidi** [comment]
@ronhippler even with the v0.41.0, there are errors due to [deno_plugin_preparev0.3.1](https://github.com/manyuanrong/deno-plugin-prepare/issues/11) does not use tags in `mod.ts` and use v0.42.0 by default.

**Comment by manyuanrong** [comment]
Use deno@v1.0.0 and deno_mongo@v0.6.0
And specify the --unstable flag
