### ISSUE TITLE
encountered 6 errors in windows machine (deno latest release v1.0.0rc)

### ISSUE THREAD

**Issue by WhoAdarshPandya** [manyuanrong/deno_mongo#14]
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
let dispatcher: Deno.PluginOp | null = null;
                     ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:7:22

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  dispatcher = Mongo.ops["mongo_command"] as Deno.PluginOp;
                                                  ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:32:51

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'OperatingSystem'.
const PLUGIN_SUFFIX_MAP: { [os in Deno.OperatingSystem]: string } = {
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:9:40

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type '"darwin" | "linux" | "windows"' can't be used to index type '{ mac?: string | undefined; linux?: string | undefined; 
win?: string | undefined; }'.
  Property 'darwin' does not exist on type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  const remoteUrl = urls[os];
                    ~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:35:21

TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);
              ~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:58:15

Found 5 errors.

C:\Users\DC\Desktop\deno>deno run -A deno-mongo.ts
Compile file:///C:/Users/DC/Desktop/deno/deno-mongo.ts
error: TS2304 [ERROR]: Cannot find name 'getClient'.
const db = getClient().database("test");
           ~~~~~~~~~
    at file:///C:/Users/DC/Desktop/deno/deno-mongo.ts:9:12

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
let dispatcher: Deno.PluginOp | null = null;
                     ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:7:22

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  dispatcher = Mongo.ops["mongo_command"] as Deno.PluginOp;
                                                  ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:32:51

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'OperatingSystem'.
const PLUGIN_SUFFIX_MAP: { [os in Deno.OperatingSystem]: string } = {
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:9:40

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type '"darwin" | "linux" | "windows"' can't be used to index type '{ mac?: string | undefined; linux?: string | undefined; 
win?: string | undefined; }'.
  Property 'darwin' does not exist on type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  const remoteUrl = urls[os];
                    ~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:35:21

TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);

C:\Users\DC\Desktop\deno>deno run -A deno-mongo.ts
Compile file:///C:/Users/DC/Desktop/deno/deno-mongo.ts
error: TS2304 [ERROR]: Cannot find name 'getClient'.      
const db = getClient().database("test");
           ~~~~~~~~~
    at file:///C:/Users/DC/Desktop/deno/deno-mongo.ts:9:12

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
let dispatcher: Deno.PluginOp | null = null;
                     ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:7:22

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  dispatcher = Mongo.ops["mongo_command"] as Deno.PluginOp;
                                                  ~~~~~~~~
    at https://deno.land/x/mongo@v0.5.2/ts/util.ts:32:51

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'OperatingSystem'.
const PLUGIN_SUFFIX_MAP: { [os in Deno.OperatingSystem]: string } = {
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:9:40

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type '"darwin" | "linux" | "windows"' can't be used to index type '{ mac?: string | undefined; linux?: string | undefined; 
win?: string | undefined; }'.
  Property 'darwin' does not exist on type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  const remoteUrl = urls[os];
                    ~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:35:21

TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);
              ~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:58:15

Found 6 errors.

**Comment by manyuanrong** [comment]
The latest version of Deno cannot be used, because the recent API is incompatible and changed a lot, and the official plugin API has not been released at the same time, so there is currently no way to upgrade normally to fix the problem. Maybe only after 1.0 is officially released

**Comment by manyuanrong** [comment]
Use deno@v1.0.0 and deno_mongo@v0.6.0
And specify the --unstable flag
