### ISSUE TITLE
when following the example with code below, the line referenced is throwing assertion error

### ISSUE THREAD

**Issue by closet6** [manyuanrong/deno_mongo#150]
```
import { Bson, MongoClient } from "../deps.ts";

const client = new MongoClient();
client.connect("mongodb://btab_db_1:27017");

const mdb = client.database("burrito");  // -> error thrown here

interface UserSchema {
  _id: { $oid: string };
  username: string;
  name: string;
  email: string;
}

const users = mdb.collection<UserSchema>("users");
```

```
web_1  | error: Uncaught AssertionError
web_1  |     throw new AssertionError(msg);
web_1  |           ^
web_1  |     at assert (asserts.ts:152:11)
web_1  |     at MongoClient.database (client.ts:48:5)
web_1  |     at main.ts:8:20
web_1  |     at <anonymous> (<anonymous>)
```

https://github.com/manyuanrong/deno_mongo/blob/70033e3917f523f7dde5042f0d3291e1e8877fab/src/client.ts#L48

**Comment by manyuanrong** [comment]
await client.connect()
