### ISSUE TITLE
The official example does not work on Linux "Debian 9"

### ISSUE THREAD

**Issue by JorgeLuis** [manyuanrong/deno_mongo#47]
Hi, run the example program on W10 and it worked OK. But, when I want to run the same program on Debian. The following error appears:

```
thread '<unnamed>' panicked at 'called `Option :: unwrap ()` on a `None` value', src / command / connect.rs: 63: 24
note: run with `RUST_BACKTRACE = 1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

I have installed:
-   deno 1.0.5
-     v8 8.4.300
-      typescript 3.9.2

With:

- MongoDB shell version v4.2.3
- distmod: debian92
- distarch: x86_64
- target_arch: x86_64

Please, someone explain the error and how it is solved.

**Comment by MeisterTea** [comment]
please rename to "The official example does not work on Linux"

It's the same with arch, etc...

**Comment by manyuanrong** [comment]
I just built a new v0.8.0 under deno v1.0.5 yesterday, you can try again

**Comment by aaronwlee** [comment]
sorry but It's still not working
```
thread 'main' panicked at 'Op already registered: mongo_command', <::std::macros::panic macros>:2:4
stack backtrace:
   0:     0x55b1c11afab4 - backtrace::backtrace::libunwind::trace::h5ae3454ebe40b621
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55b1c11afab4 - backtrace::backtrace::trace_unsynchronized::hbf6f267a483fb2c0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55b1c11afab4 - std::sys_common::backtrace::_print_fmt::h37755015d94b9085
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55b1c11afab4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0561c8cd3569b40d
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b1c11dadec - core::fmt::write::h86a597a35d48a212
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55b1c11a6ea3 - std::io::Write::write_fmt::h73d9dc0f29eefe48
                               at src/libstd/io/mod.rs:1426
   6:     0x55b1c11b2a45 - std::sys_common::backtrace::_print::h6c60c5ee09af0233
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b1c11b2a45 - std::sys_common::backtrace::print::hf9d1db01634f9b2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b1c11b2a45 - std::panicking::default_hook::{{closure}}::h1db9298dd213ae95
                               at src/libstd/panicking.rs:204
   9:     0x55b1c11b2792 - std::panicking::default_hook::h3272faf6cc91fd2e
                               at src/libstd/panicking.rs:224
  10:     0x55b1c11b30a2 - std::panicking::rust_panic_with_hook::hb976084785e50594
                               at src/libstd/panicking.rs:470
  11:     0x55b1bff69ad3 - std::panicking::begin_panic::h53bb99d2ad46dbce
  12:     0x55b1bfdd663b - deno_core::ops::OpRegistry::register::h7b8f39224df8bd9c
  13:     0x55b1bff5387a - deno::ops::plugin::op_open_plugin::ha0f9cc05ac141964
  14:     0x55b1bfe01a3e - deno::state::State::core_op::{{closure}}::he51ec4d67c65191b
  15:     0x55b1c0648ec1 - deno_core::core_isolate::CoreIsolateState::dispatch_op::h658f6019c5c74f37
  16:     0x55b1c0659cb6 - deno_core::bindings::send::h1950a079d593969b
  17:     0x55b1c066e1bf - <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn::h40a6ebc8c1300426
  18:     0x55b1c0c89529 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  19:     0x55b1c0c88a04 - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  20:     0x55b1c0c8808f - _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
  21:     0x55b1c0b75298 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
fatal runtime error: failed to initiate panic, error 5
Aborted
```

**Comment by JorgeLuis** [comment]
Solved, thank you very much !!! I had no problems with a single server. Then I did the test in a replica and it worked, but I had to implement "connectWithOptions", if you can put together an official example I would appreciate it.
Congratulations on the work!
Greetings Jorge Luis
