### ISSUE TITLE
Error on windows - Rust error

### ISSUE THREAD

**Issue by MatteoGauthier** [manyuanrong/deno_mongo#64]
```
Microsoft Windows [version 10.0.18363.900]
deno 1.1.3
v8 8.5.216
typescript 3.9.2
```

```
INFO load deno plugin "deno_mongo" from local "D:\WorkFolder\Devlopment\Peoples Project\Deno\deno-rest-api\.deno_plugins\deno_mongo_7117ccb53f8978e745db83130ae27b42.dll"
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\command\connect.rs:63:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault
```

**Comment by nshusr** [comment]
And it's not just windows,MacOS, it's a mistake
```
[denon] starting `deno run --allow-net --allow-read --allow-write --allow-plugin --unstable app.ts`
INFO load deno plugin "deno_mongo" from local "project/.deno_plugins/deno_mongo_8834e91d4661df9888ff57240f3b8a4c.dylib"
INFO load deno plugin "deno_mongo" from local "project/.deno_plugins/deno_mongo_8834e91d4661df9888ff57240f3b8a4c.dylib"
thread 'main' panicked at 'Op already registered: mongo_command', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/macros.rs:13:23
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: <deno::ops::plugin::PluginInterface as deno_core::plugin_api::Interface>::register_op
   8: deno::state::State::core_op::{{closure}}
   9: deno_core::core_isolate::CoreIsolateState::dispatch_op
  10: deno_core::bindings::send
  11: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
  12: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  13: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  14: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

**Comment by lucacasonato** [comment]
You seem to be loading two different versions of deno_mongo. Check with `deno info` that you are loading just one version of the module.

**Comment by manyuanrong** [comment]
@lucacasonato 
I think we can `register_op_${verstion}` to avoid the problem of multi-version dependencies, so that multiple versions can work at the same time, because there seems to be no way to avoid multiple upstream versions using multiple different versions.
I am glad that I initially decided to use a single `register_op` to proxy all the APIs, which makes it easy to implement this
