### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientId' of undefined

### ISSUE THREAD

**Issue by hylerrix** [manyuanrong/deno_mongo#85]
## Error

```
INFO load deno plugin "deno_mongo" from local "/Users/didi/WorkSpace/Hylerrix/deno-app-starter/packages/das-template-oak-graphql/template/.deno_plugins/deno_mongo_8834e91d4661df9888ff57240f3b8a4c.dylib"
error: Uncaught TypeError: Cannot read property 'clientId' of undefined
    this._clientId = data.clientId;
                          ^
    at MongoClient.connectWithUri (client.ts:105:27)
    at db.ts:14:8
    at <anonymous> (<anonymous>)
 M: got status of process with pid 2855
 M: process with pid 2855 exited on its own
[denon] app crashed - waiting for file changes before starting ...
```

## Source Code

```bash
deno 1.1.3
v8 8.5.216
typescript 3.9.2
```

```bash
$ deno run --allow-env --allow-net --allow-read --allow-write --allow-plugin --importmap import_map.json --unstable app.ts
```

app.ts use GraphQL, and one of its resolvers: `import { todos } from "../db/db.ts"`

`db.ts`:

```typescript
import { MongoClient } from "mongo"

const dbName = "das"
const dbHostUrl = "mongodb://localhost:27017"

interface TodoSchema {
  _id: { $oid: string }
  name: string
  done: boolean
}

const client = new MongoClient()
client.connectWithUri(dbHostUrl)
const db = client.database(dbName)
const todos = db.collection<TodoSchema>("todos")

export { db, todos }
```

And MongoDB has no username and password, the das database exists.

![](https://user-images.githubusercontent.com/19285461/88649230-466a6280-d0fa-11ea-9aae-05c95f365b51.png)

**Comment by manyuanrong** [comment]
outdate
