### ISSUE TITLE
Where did release 0.10.0 disappear?

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [manyuanrong/deno_mongo#95]
Today I was targeting `https://deno.land/x/mongo@v0.10.0/mod.ts` as specified in the latest documentation but suddenly it just disappeared after 0.10.1 was introduced. After switching to 0.10.1 I get this error:

```
error: Uncaught Error: downloading plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releas
es/download/v0.10.0/deno_mongo.dll" failed.
    throw Error(`downloading plugin "${name}" from "${remoteUrl}" failed.`);
          ^
    at downloadFromRemote (mod.ts:76:11)
    at async download (mod.ts:46:7)
    at async prepare (mod.ts:60:21)
    at async init (util.ts:44:3)
    at async mod.ts:13:1

```

Clearly, there is something wrong here in the dependencies

**Comment by AndrewBogdanovTSS** [comment]
Fixed now, thanks
